### ISSUE TITLE
package not found by name

### ISSUE THREAD

**Issue by korenmiklos** [krisztianfekete/lib#27]
I downloaded a neuron package zip to my local repo. Afterwards, I issued `neuron input add`, and got the error message above.

```
CEU-8706:managerdb koren$ neuron repo list
Repositories:
-------------
sandbox: /Volumes/Home/xl/data/data-repo/repositories
local: /Volumes/Home/datastore/neuron-repos
CEU-8706:managerdb koren$ pwd
/Volumes/Home/datastore/managerdb
CEU-8706:managerdb koren$ neuron repo list
Repositories:
-------------
sandbox: /Volumes/Home/xl/data/data-repo/repositories
local: /Volumes/Home/datastore/neuron-repos
CEU-8706:managerdb koren$ neuron input add frame frame
ERROR: Not a known package name: frame
CEU-8706:managerdb koren$ ls /Volumes/Home/datastore/neuron-repos/
frame_20151028_152234_226060.zip	rovat_13_15_20151105_144001_928190.zip
CEU-8706:managerdb koren$ 
```

**Comment by krisztianfekete** [comment]
Names are not derived from file names - they are independent, you can rename the zip files to whatever you want, they will be still found or not.

In this case the name `frame` is not mapped to the package uuid of the concrete zip file.
Name export, import is a new command line feature, that was not implemented in the neuron binary.

Try
`neuron input add frame /Volumes/Home/datastore/neuron-repos/frame_20151028_152234_226060.zip`
